### ISSUE TITLE
Font Validator warning w2106: OS/2 table version

### ISSUE THREAD

**Issue by JBrase** [silnrsi/font-taiheritagepro#2]
FV warning: W2106. The version number is valid, but less than 5.
See "[Font Validator results for THP 2.6](https://docs.google.com/spreadsheets/d/10haYwkXMqCluXcxY9v1tm2zNEW25e85qEDNJQjCoIws/edit#gid=595904387)"
Does this need to be corrected in FL?

**Comment by jvgaultney** [comment]
This is not controllable in FL, and seems to be the OS/2 version FL5 generates by default. It can be ignored I think.

**Comment by bobh0303** [comment]
I agree.  Feel free to close this issue.
