### ISSUE TITLE
Font Validator warning W2116. usWeightClass vs PANOSE weight value

### ISSUE THREAD

**Issue by JBrase** [silnrsi/font-taiheritagepro#3]
FV warning: W2116 The usWeightClass is inconsistent with the PANOSE weight value. usWeightClass = 700, PANOSE weight = 6
Does this need to be corrected in FL?

**Comment by jvgaultney** [comment]
Is this in Bold? usWeightClass should be 400 in regular, 700 in bold and PANOSE weight should be 6 for regular 8 for bold. I'd check this myself but the FL source file is not in this repo - only the ttfs.

**Comment by JBrase** [comment]
Yes. This is for the bold.
